-- Demo table for multi-MCP BigQuery + live AeroAPI flight boards (see flight MCP get_airport_flights).
-- Replace PROJECT and DATASET before running in the BigQuery console.

-- ---------------------------------------------------------------------------
-- Airports — shape aligned with AeroAPI GET /airports/{id} (flattened).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT.DATASET.airports` (
  airport_code STRING NOT NULL,
  alternate_ident STRING,
  code_icao STRING,
  code_iata STRING,
  code_lid STRING,
  name STRING,
  type STRING,
  elevation INT64,
  city STRING,
  state STRING,
  longitude FLOAT64,
  latitude FLOAT64,
  timezone STRING,
  country_code STRING,
  wiki_url STRING,
  airport_flights_url STRING,
  airport_info_url STRING
);

INSERT INTO `PROJECT.DATASET.airports` (
  airport_code,
  alternate_ident,
  code_icao,
  code_iata,
  code_lid,
  name,
  type,
  elevation,
  city,
  state,
  longitude,
  latitude,
  timezone,
  country_code,
  wiki_url,
  airport_flights_url,
  airport_info_url
)
VALUES
  (
    '00AA',
    '00AA',
    NULL,
    NULL,
    '00AA',
    'Aero B Ranch',
    'Airport',
    3435,
    'Leoti',
    'KS',
    -101.4739111,
    38.7040222,
    'America/Chicago',
    'US',
    NULL,
    '/airports/00AA/flights',
    '/airports/00AA'
  ),
  (
    '00AK',
    '00AK',
    NULL,
    NULL,
    '00AK',
    'Lowell Fld',
    'Airport',
    252,
    'Anchor Point',
    'AK',
    -151.6922222,
    59.9488889,
    'America/Anchorage',
    'US',
    NULL,
    '/airports/00AK/flights',
    '/airports/00AK'
  ),
  (
    '00AL',
    '00AL',
    NULL,
    NULL,
    '00AL',
    'Epps Airpark',
    'Airport',
    820,
    'Harvest',
    'AL',
    -86.7702775,
    34.8648103,
    'America/Chicago',
    'US',
    NULL,
    '/airports/00AL/flights',
    '/airports/00AL'
  ),
  (
    '00AN',
    '00AN',
    NULL,
    NULL,
    '00AN',
    'Katmai Lodge',
    'Airport',
    80,
    'King Salmon',
    'AK',
    -156.4558333,
    59.0934722,
    'America/Anchorage',
    'US',
    NULL,
    '/airports/00AN/flights',
    '/airports/00AN'
  ),
  (
    '00AR',
    '00AR',
    NULL,
    NULL,
    '00AR',
    'Arland',
    'Airport',
    1352,
    'Bennington',
    'KS',
    -97.6015566,
    38.9696511,
    'America/Chicago',
    'US',
    NULL,
    '/airports/00AR/flights',
    '/airports/00AR'
  ),
  (
    '00C',
    '00C',
    NULL,
    NULL,
    '00C',
    'Animas Air Park',
    'Airport',
    6684,
    'Durango',
    'CO',
    -107.8691953,
    37.2031783,
    'America/Denver',
    'US',
    'https://en.wikipedia.org/wiki/Animas_Air_Park',
    '/airports/00C/flights',
    '/airports/00C'
  ),
  (
    'KHOU',
    NULL,
    'KHOU',
    'HOU',
    'HOU',
    'William P Hobby',
    'Airport',
    46,
    'Houston',
    'TX',
    -95.278889,
    29.645419,
    'America/Chicago',
    'US',
    NULL,
    '/airports/KHOU/flights',
    '/airports/KHOU'
  ),
  (
    'KIAH',
    NULL,
    'KIAH',
    'IAH',
    'IAH',
    'Houston Bush Int''ctl',
    'Airport',
    97,
    'Houston',
    'TX',
    -95.341442,
    29.984435,
    'America/Chicago',
    'US',
    NULL,
    '/airports/KIAH/flights',
    '/airports/KIAH'
  ),
  (
    'KSFO',
    NULL,
    'KSFO',
    'SFO',
    'SFO',
    'San Francisco Int''l',
    'Airport',
    13,
    'San Francisco',
    'CA',
    -122.374889,
    37.618972,
    'America/Los_Angeles',
    'US',
    NULL,
    '/airports/KSFO/flights',
    '/airports/KSFO'
  );

